
/**
 * Generates a Markdown report from the analysis artifacts and triggers a download.
 * @param artifacts The array of artifacts generated by the agents.
 * @param filename The name of the file to save (default: "report.md").
 */
export function downloadReport(artifacts: any[], filename: string = "report.md") {
    if (!artifacts || artifacts.length === 0) {
        alert("No artifacts to export.");
        return;
    }

    let reportContent = "# Intelligent Analysis Report\n\n";
    reportContent += `Generated on: ${new Date().toLocaleString()}\n\n`;

    artifacts.forEach((art, index) => {
        reportContent += `## ${index + 1}. ${art.filename}\n\n`;

        // Insight/Observation
        if (art.insight) {
            if (art.insight.observation) {
                reportContent += `### Observation\n${art.insight.observation}\n\n`;
            }
            if (art.insight.insight) {
                reportContent += `### Key Insight\n${art.insight.insight}\n\n`;
            }
            if (art.insight.actionable && Array.isArray(art.insight.actionable)) {
                reportContent += `### Recommendations\n`;
                art.insight.actionable.forEach((action: string) => {
                    reportContent += `- ${action}\n`;
                });
                reportContent += "\n";
            }
        }

        // Image placeholder (Images cannot be directly embedded in a simple text file download 
        // without more complex packaging like HTML or PDF, but we can add a placeholder)
        if (art.content) {
            reportContent += `*[Image generated: ${art.filename}]*\n\n`;
        }

        reportContent += "---\n\n";
    });

    // Create blob and link
    const blob = new Blob([reportContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
